test:8.8.4:
    image: haskell:8.8.4
    script:
        - cabal new-build --enable-tests --enable-benchmarks --test-show-details=streaming
        - cabal new-test --enable-tests --enable-benchmarks --test-show-details=streaming
