name:                swiss-ephemeris
version:             0.1.0.0
github:              "lfborjas/swiss-ephemeris"
license:             GPL-2
author:              "Luis Borjas Reyes"
maintainer:          "luis@lfborjas.com"
copyright:           "2020 Luis Borjas Reyes"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Haskell bindings for the Swiss Ephemeris C library
category:            Data

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/lfborjas/swiss-ephemeris#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  c-sources:
    - csrc/swecl.c
    - csrc/swedate.c
    - csrc/swehel.c
    - csrc/swehouse.c
    - csrc/swejpl.c
    - csrc/swemmoon.c
    - csrc/swemplan.c
    - csrc/swepcalc.c
    - csrc/swepdate.c
    - csrc/sweph.c
    - csrc/swephlib.c
  include-dirs: csrc

tests:
  swiss-ephemeris-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - swiss-ephemeris
    - hspec
    - directory
    build-tools:
    - hspec-discover
